# Source: nestjs-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-nestjs-app-primary-service  # Ensure the service name is unique
  labels:
    helm.sh/chart: nestjs-app-0.1.0
    app.kubernetes.io/name: my-nestjs-app-primary  # Update to match the new deployment name
    app.kubernetes.io/instance: my-nestjs-app-primary
    app.kubernetes.io/part-of: nestjs-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: my-nestjs-app-primary  # Match with the deployment
